<?php
use GoatPen\ViewHelpers\ActionsNavigation;
use GoatPen\{Metric, Platform};
use LaravelGems\Escape\HTML;

$actions = new ActionsNavigation;

if ($metric->exists) {
    $actions->add('History', '/metrics/' . $metric->id . '/history', 'history');
    $actions->add('Delete', '/metrics/' . $metric->id . '/delete', 'trash');
}

echo $this->fetch('/partials/header.phtml', [
    'pageTitle' => ($metric->exists ? 'Edit metric' : 'New metric'),
    'actions'   => $actions,
]);
?>

<form class="form-horizontal" method="post">
    <div class="form-group">
        <label for="name" class="col-sm-2 control-label">Name</label>

        <div class="col-sm-10">
            <input class="form-control" name="name" id="name" placeholder="Name" value="<?= HTML::attr($metric->name); ?>" required>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Type</label>

        <div class="col-sm-10">
            <?php
            foreach (Metric::TYPES as $type) {
                echo sprintf(
                    '<label class="radio-inline"><input type="radio" name="type" value="%s" %s>%s</label>',
                    HTML::attr($type),
                    ($type === $metric->type ? 'checked' : ''),
                    HTML::text($type)
                );
            }
            ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Scope</label>

        <div class="col-sm-10">
            <?php
            foreach (Metric::SCOPES as $scope) {
                echo sprintf(
                    '<label class="radio-inline"><input type="radio" name="scope" value="%s" %s>%s</label>',
                    HTML::attr($scope),
                    ($scope === $metric->scope ? 'checked' : ''),
                    HTML::text($scope)
                );
            }
            ?>
        </div>
    </div>

    <div class="form-group">
        <label for="stats" class="col-sm-2 control-label">Channel-level</label>

        <div class="col-sm-10">
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="stats" id="stats" <?= ($metric->stats ? 'checked' : ''); ?>>
                </label>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label for="automated" class="col-sm-2 control-label">Automated</label>

        <div class="col-sm-10">
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="automated" id="automated" <?= ($metric->automated ? 'checked' : ''); ?>>
                </label>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Platforms</label>

        <div class="col-sm-10">
            <div class="checkbox">
                <ul class="list-unstyled">
                    <?php
                    $platforms = Platform::orderBy('order', 'asc');

                    foreach ($platforms->get() as $platform) {
                    ?>
                        <li>
                            <label>
                                <input type="checkbox" name="platform_id[]" value="<?= $platform->id; ?>" <?= (in_array($platform->id, $platform_ids) ? 'checked' : ''); ?>>
                                <?= HTML::text($platform->name); ?>
                            </label>
                        </li>
                    <?php
                    }
                    ?>
                </ul>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="hidden" name="<?= $csrf->getTokenNameKey(); ?>" value="<?= $csrf->getTokenName(); ?>">
            <input type="hidden" name="<?= $csrf->getTokenValueKey(); ?>" value="<?= $csrf->getTokenValue(); ?>">
            <button class="btn btn-default">Save</button>
        </div>
    </div>
</form>

<?= $this->fetch('/partials/footer.phtml'); ?>
