<?php
use GoatPen\Services\CacheBuster;
use GoatPen\Session;
use GoatPen\ViewHelpers\Notification;
use LaravelGems\Escape\HTML;
?>

<!DOCTYPE html>

<html lang="en" class="mode-<?= ENV; ?>">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex,nofollow">

    <title><?= HTML::text($pageTitle ?? 'Goat Pen'); ?></title>

    <link rel="icon" href="/images/favicon.ico">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/lib/jquery-comments/jquery-comments.css">
    <link rel="stylesheet" href="<?= CacheBuster::getPath('/css/base.css'); ?>">

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="/lib/jquery/jquery-ui.min.js"></script>
    <script src="https://use.fontawesome.com/b56362b157.js"></script>
    <script src="/lib/jquery-comments/jquery-comments.min.js"></script>
    <link rel="stylesheet" href="<?= CacheBuster::getPath('/css/client-dashboard.css'); ?>">
    <script src="/js/csrf.js"></script>
</head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <i class="fa fa-bars"></i>
                </button>

                <a class="navbar-brand" href="/dashboard"><img src="/images/goat-logo.png" height="40"></a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav client-dashboard">
                    <li>
                        <p class="client-title">
                            <i class="fa fa-lg fa-tachometer"></i>
                            Client Dashboard
                        </p>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <?php
                    if (Session::getUser()->owner) {
                    ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-lg fa-user"></i> &nbsp User <i class="fa fa-caret-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="/users">Users</a></li>
                                <li><a href="/sheets-reload">Refresh data from Google Spreadsheets</a></li>
                            </ul>
                        </li>
                    <?php
                    }
                    ?>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <?php
        echo Notification::render();

        if (($showTitle ?? true) === true) {
            ?>
            <div class="page-header">
                <h1>
                    <?php
                    echo HTML::text($pageTitle);

                    if (isset($actions)) {
                        ?>
                        <ul class="list-inline pull-right actions">
                            <?php
                            foreach ($actions->get() as $item) {
                                echo '<li>' . $item . '</li>' . PHP_EOL;
                            }
                            ?>
                        </ul>
                        <?php
                    } elseif (isset($updatedAt)) {
                        ?>
                        <div class="pull-right">
                            <p class="h3 mg-0">LAST REFRESHED AT:</p>
                            <p class="header-date mg-0"><?= $updatedAt['date']; ?> <?= $updatedAt['time']; ?></p>
                        </div>
                        <?php
                    }
                    ?>
                </h1>
            </div>
            <?php
        }
        ?>

        <div id="page-content">
