<?php
use GoatPen\ViewHelpers\ActionsNavigation;

echo $this->fetch('/partials/header.phtml', [
    'pageTitle' => 'Import posts for \'' . $campaign->name . '\'',
    'actions'   => (new ActionsNavigation)->add('History', '/campaigns/import/history', 'history'),
]);
?>

<form class="form-horizontal" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="type" class="col-sm-2 control-label">Type</label>

        <div class="col-sm-10">
            <p class="form-control-static">
                <select name="type" id="type">
                    <option value="content">Content (post-level)</option>
                    <option value="stats">Stats (channel-level)</option>
                </select>
            </p>
        </div>
    </div>

    <div class="form-group">
        <label for="file" class="col-sm-2 control-label">CSV file</label>

        <div class="col-sm-10">
            <p class="form-control-static">
                <input type="file" name="file" id="file" accept="text/csv" required>
            </p>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="hidden" name="<?= $csrf->getTokenNameKey(); ?>" value="<?= $csrf->getTokenName(); ?>">
            <input type="hidden" name="<?= $csrf->getTokenValueKey(); ?>" value="<?= $csrf->getTokenValue(); ?>">
            <button class="btn btn-default">Import</button>
        </div>
    </div>
</form>

<?= $this->fetch('/partials/footer.phtml'); ?>
