<?php
use GoatPen\ViewHelpers\ActionsNavigation;
use LaravelGems\Escape\HTML;

echo $this->fetch('/partials/header.phtml', [
    'pageTitle' => 'Campaigns',
    'actions'   => (new ActionsNavigation)->add('Add new', '/campaigns/new', 'plus'),
]);

$paginator->display();
?>

<table class="table table-condensed">
    <thead>
        <tr>
            <th>Name</th>
            <th>Client</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($campaigns as $campaign) {
        ?>
            <tr>
                <td><a href="/campaigns/<?= HTML::attr($campaign->id); ?>/edit"><?= HTML::text($campaign->name); ?></a></td>
                <td><?= HTML::text($campaign->client); ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

<?php $paginator->display(); ?>

<?= $this->fetch('/partials/footer.phtml'); ?>
