<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex,nofollow">

    <title>403 Forbidden</title>

    <link rel="icon" href="/images/favicon.ico">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css">

    <script src="https://use.fontawesome.com/b56362b157.js"></script>

    <style>
        .jumbotron {
            background: none;
        }

        .text-danger {
            color: #d9534f;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="jumbotron text-center">
            <h1>
                <i class="fa fa-ban text-danger"></i>
                403 Forbidden
            </h1>

            <p class="lead">Sorry! You don't have access permissions for that on <em>goatpen.io</em>.</p>

            <p><a class="btn btn-success btn-lg" href="/">Take me to the homepage</a></p>
        </div>

        <div class="row">
            <div class="col-sm-6">
                <h2>What happened?</h2>

                <p class="lead">A 403 error status indicates that you don't have permission to access the file or page. In general, web servers and websites have directories and files that are not open to the public web for security reasons.</p>
            </div>

            <div class="col-sm-6">
                <h2>What can I do?</h2>

                <p class="lead">If you're a site visitor</p>

                <p>Please use your browser's back button and check that you're in the right place. If you need immediate assistance, please send us an email instead.</p>

                <p class="lead">If you're the site owner</p>

                <p>Please check that you're in the right place and get in touch with your website provider if you believe this to be an error.</p>
            </div>
        </div>
    </div>
</body>

</html>
