<?php
use GoatPen\Services\CacheBuster;
use GoatPen\ViewHelpers\{ActionsNavigation, CountryCodes, Tag};
use GoatPen\{Influencer, InfluencerTrait};
use LaravelGems\Escape\HTML;

$actions = new ActionsNavigation;

if ($influencer->exists) {
    $actions->add('Delete', '/influencers/' . $influencer->id . '/delete', 'trash');
}

echo $this->fetch('/partials/header.phtml', [
    'pageTitle' => ($influencer->exists ? 'Edit influencer' : 'New influencer'),
    'actions'   => $actions,
]);
?>

<form class="form-horizontal" method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Main details</h3>
        </div>

        <div class="panel-body">
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">Name</label>

                <div class="col-sm-10">
                    <input class="form-control" name="name" id="name" placeholder="Name" value="<?= HTML::attr($influencer->name); ?>" required>
                </div>
            </div>

            <div class="form-group">
                <label for="email" class="col-sm-2 control-label">Email</label>

                <div class="col-sm-10">
                    <input type="email" class="form-control" name="email" id="email" placeholder="Email" value="<?= HTML::attr($influencer->email); ?>">
                </div>
            </div>

            <div class="form-group">
                <label for="phone" class="col-sm-2 control-label">Phone</label>

                <div class="col-sm-10">
                    <input type="tel" class="form-control" name="phone" id="phone" placeholder="Phone" value="<?= HTML::attr($influencer->phone); ?>">
                </div>
            </div>

            <div class="form-group">
                <label for="gender" class="col-sm-2 control-label">Gender</label>

                <div class="col-sm-10">
                    <select class="form-control" name="gender" id="gender">
                        <option value="">-</option>
                        <?php
                        echo implode(array_map(function ($gender) use ($influencer) {
                            return (
                                $gender === $influencer->gender
                                ? sprintf('<option value="%s" selected>%s</option>', HTML::attr($gender), HTML::text($gender))
                                : sprintf('<option value="%s">%s</option>', HTML::attr($gender), HTML::text($gender))
                                ) . PHP_EOL;
                        }, Influencer::GENDERS));
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="age_group" class="col-sm-2 control-label">Age group</label>

                <div class="col-sm-10">
                    <select class="form-control" name="age_group" id="age_group">
                        <option value="">-</option>
                        <?php
                        echo implode(array_map(function ($group) use ($influencer) {
                            return (
                                $group === $influencer->age_group
                                    ? sprintf('<option value="%s" selected>%s</option>', HTML::attr($group), HTML::text($group))
                                    : sprintf('<option value="%s">%s</option>', HTML::attr($group), HTML::text($group))
                                ) . PHP_EOL;
                        }, Influencer::AGE_GROUPS));
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="location" class="col-sm-2 control-label">Location</label>

                <div class="col-sm-10">
                    <select class="form-control" name="location" id="location">
                        <option value="">-</option>
                        <?php
                        echo implode(array_map(function($country, $code) use ($influencer) {
                            return (
                                $code === $influencer->location
                                ? sprintf('<option value="%s" selected>%s</option>', HTML::attr($code), HTML::text($country))
                                : sprintf('<option value="%s">%s</option>', HTML::attr($code), HTML::text($country))
                            ) . PHP_EOL;
                        }, CountryCodes::countries(), CountryCodes::codes()));
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="nationality" class="col-sm-2 control-label">Nationality</label>

                <div class="col-sm-10">
                    <select class="form-control" name="nationality" id="nationality">
                        <option value="">-</option>
                        <?php
                        echo implode(array_map(function($country, $code) use ($influencer) {
                            return (
                                $code === $influencer->nationality
                                ? sprintf('<option value="%s" selected>%s</option>', HTML::attr($code), HTML::text($country))
                                : sprintf('<option value="%s">%s</option>', HTML::attr($code), HTML::text($country))
                            ) . PHP_EOL;
                        }, CountryCodes::countries(), CountryCodes::codes()));
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="user_id" class="col-sm-2 control-label">Primary contact</label>

                <div class="col-sm-10">
                    <select class="form-control" name="user_id" id="user_id">
                        <option value="">-</option>
                        <?php
                        foreach ($users->pluck('name', 'id')->toArray() as $id => $name) {
                            echo sprintf(
                                '<option value="%d" %s>%s</option>',
                                HTML::attr($id),
                                ($influencer->user_id === $id ? 'selected' : ''),
                                HTML::text($name)
                            );
                        }
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="secondary_user_id" class="col-sm-2 control-label">Secondary contact</label>

                <div class="col-sm-10">
                    <select class="form-control" name="secondary_user_id" id="secondary_user_id">
                        <option value="">-</option>
                        <?php
                        foreach ($users->pluck('name', 'id')->toArray() as $id => $name) {
                            echo sprintf(
                                '<option value="%d" %s>%s</option>',
                                HTML::attr($id),
                                ($influencer->secondary_user_id === $id ? 'selected' : ''),
                                HTML::text($name)
                            );
                        }
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label" for="primary_tag">Primary tag</label>

                <div class="col-sm-10">
                    <input class="form-control" name="primary_tag" id="primary_tag" list="tags-list" value="<?= HTML::attr($influencer->primary_tag); ?>">
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Tags</label>

                <div class="col-sm-10">
                    <ul class="list-unstyled" id="tags">
                        <?php
                        $tags   = $influencer->tags ?? [];
                        $tags[] = null;

                        foreach ($tags as $tag) {
                        ?>
                            <li class="tag">
                                <input class="form-control" name="tag[]" list="tags-list" value="<?= HTML::attr($tag); ?>">
                            </li>
                        <?php
                        }
                        ?>
                    </ul>

                    <datalist id="tags-list">
                        <?php
                        foreach (Tag::all() as $tag) {
                        ?>
                            <option value="<?= HTML::attr($tag); ?>">
                        <?php
                        }
                        ?>
                    </datalist>

                    <p>
                        <a class="btn btn-default" href="#" id="add-tag">
                            <i class="fa fa-plus"></i>
                            Add another tag
                        </a>
                    </p>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Traits</label>

                <div class="col-sm-10">
                    <div class="checkbox">
                        <ul class="list-unstyled">
                            <?php
                            $traits = InfluencerTrait::query()->orderBy('name', 'asc');

                            foreach ($traits->get() as $trait) {
                                ?>
                                <li>
                                    <label>
                                        <input type="checkbox" name="trait_id[]" value="<?= $trait->getKey(); ?>" <?= (in_array($trait->getKey(), $trait_ids) ? 'checked' : ''); ?>>
                                        <?= HTML::text($trait->name); ?>
                                    </label>
                                </li>
                                <?php
                            }
                            ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="channels">
        <?php
        $count = 1;

        foreach ($channels as $channel) {
            $channel_id = ($channel->exists ? $channel->id : 'new_' . $count);
            ?>
            <div class="panel panel-default channel" data-count="<?= $count; ?>">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Channel #<span class="count"><?= $count; ?></span>

                        <?php
                        if ($channel->exists) {
                        ?>
                            <a class="text-danger pull-right delete" href="/influencers/<?= $influencer->id; ?>/channels/<?= $channel_id; ?>/delete">
                                Delete
                            </a>
                        <?php
                        }
                        ?>
                    </h3>
                </div>

                <div class="panel-body">
                    <?php
                    if ($channel->error !== null) {
                        ?>
                        <div class="alert alert-danger">
                            <?= Html::text($channel->error); ?>
                        </div>
                        <?php
                    }
                    ?>

                    <div class="form-group">
                        <label for="channel_name_<?= $channel_id; ?>" class="col-sm-2 control-label">Name</label>

                        <div class="col-sm-10">
                            <input class="form-control" name="channel[<?= $channel_id; ?>][name]" id="channel_name_<?= $channel_id; ?>" placeholder="Name" value="<?= HTML::attr($channel->name); ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="channel_url_<?= $channel_id; ?>" class="col-sm-2 control-label">URL</label>

                        <div class="col-sm-10">
                            <input class="form-control" name="channel[<?= $channel_id; ?>][url]" id="channel_url_<?= $channel_id; ?>" placeholder="URL" value="<?= HTML::attr($channel->url); ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="channel_price_<?= $channel_id; ?>" class="col-sm-2 control-label">Price</label>

                        <div class="col-sm-5">
                            <div class="input-group">
                                <span class="input-group-addon">£</span>
                                <input type="number" min="0" max="100000" step="0.01" class="form-control" name="channel[<?= $channel_id; ?>][price]" id="channel_price_<?= $channel_id; ?>" placeholder="Price" value="<?= HTML::attr($channel->price); ?>">
                            </div>
                        </div>

                        <div class="col-sm-5">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="channel[<?= $channel_id; ?>][negotiable]" id="channel_negotiable_<?= $channel_id; ?>" <?= ($channel->negotiable ? 'checked' : ''); ?>>
                                    Negotiable?
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="channel_platform_id_<?= $channel_id; ?>" class="col-sm-2 control-label">Platform</label>

                        <div class="col-sm-10">
                            <select class="form-control" name="channel[<?= $channel_id; ?>][platform_id]" id="channel_platform_id_<?= $channel_id; ?>">
                                <option value="0">-</option>
                                <?php
                                foreach ($platforms->pluck('name', 'id')->toArray() as $platform_id => $name) {
                                    echo sprintf(
                                        '<option value="%d" %s>%s</option>',
                                        HTML::attr($platform_id),
                                        ($channel->platform_id === $platform_id ? 'selected' : ''),
                                        HTML::text($name)
                                    );
                                }
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group metrics <?= (! $channel->platform ? 'hidden' : ''); ?>">
                        <label class="col-sm-2 control-label">Metrics</label>

                        <div class="col-sm-10">
                            <ul class="list-inline">
                                <?php
                                foreach ($metrics as $metric) {
                                    $platform_ids = $metric->platforms()->allRelatedIds()->toArray();
                                    ?>
                                    <li class="col-sm-3 <?= ($channel->platform && ! in_array($channel->platform->id, $platform_ids) ? 'hidden' : ''); ?>" data-platforms=",<?= implode(',', $platform_ids); ?>,">
                                        <label for="channel_<?= $channel_id; ?>_metric_<?= $metric->id; ?>" class="control-label"><?= HTML::text($metric->name); ?></label>
                                        <input type="number" min="0" step="0.01" class="form-control" name="channel[<?= $channel_id; ?>][metric][<?= $metric->id; ?>]" id="channel_<?= $channel_id; ?>_metric_<?= $metric->id; ?>" value="<?= HTML::attr($channel->metrics[$metric->id] ?? ''); ?>">
                                    </li>
                                <?php
                                }
                                ?>
                            </ul>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Demographics</label>

                        <div class="col-sm-10">
                            <div class="demographics">
                                <?php
                                foreach ($channel->demographics ?? [] as $name => $value) {
                                    ?>
                                    <div class="form-group">
                                        <div class="col-sm-6">
                                            <input class="form-control" name="channel[<?= $channel_id; ?>][demographic][name][]" value="<?= HTML::attr($name); ?>" readonly>
                                        </div>

                                        <div class="col-sm-6">
                                            <div class="input-group">
                                                <input type="number" class="form-control" name="channel[<?= $channel_id; ?>][demographic][value][]" value="<?= HTML::attr($value); ?>" step="0.01" min="0" max="100">
                                                <span class="input-group-addon"><i class="fa fa-percent"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                    <?php
                                }
                                ?>
                                <div class="form-group demographic">
                                    <div class="col-sm-6">
                                        <select class="form-control" name="channel[<?= $channel_id; ?>][demographic][name][]">
                                            <option></option>
                                            <?php
                                            foreach ($demographics as $demographic) {
                                                ?>
                                                <optgroup label="<?= HTML::attr($demographic->name); ?>">
                                                    <?php
                                                    foreach ($demographic->groups() as $group) {
                                                        ?>
                                                        <option><?= HTML::text($group); ?></option>
                                                        <?php
                                                    }
                                                    ?>
                                                </optgroup>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="input-group">
                                            <input type="number" class="form-control" name="channel[<?= $channel_id; ?>][demographic][value][]" step="0.01" min="0" max="100">
                                            <span class="input-group-addon"><i class="fa fa-percent"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <p>
                                <a class="btn btn-default" href="#" id="add-demographic">
                                    <i class="fa fa-plus"></i>
                                    Add another demographic
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <?php
            $count++;
        }
        ?>
    </div>

    <p>
        <a class="btn btn-default" href="#" id="add-channel">
            <i class="fa fa-plus"></i>
            Add another channel
        </a>
    </p>

    <div class="form-group">
        <div class="col-sm-12">
            <input type="hidden" name="<?= $csrf->getTokenNameKey(); ?>" value="<?= $csrf->getTokenName(); ?>">
            <input type="hidden" name="<?= $csrf->getTokenValueKey(); ?>" value="<?= $csrf->getTokenValue(); ?>">
            <button class="btn btn-primary">Save</button>
        </div>
    </div>
</form>

<script src="<?= CacheBuster::getPath('/js/influencer.js'); ?>"></script>
<script src="<?= CacheBuster::getPath('/js/tags.js'); ?>"></script>
<script src="<?= CacheBuster::getPath('/js/demographics.js'); ?>"></script>

<?= $this->fetch('/partials/footer.phtml'); ?>
